
spring:
  application:
    name: fireinfo_healthcheck

  datasource:
    url: jdbc:mysql://0.0.0.0:0000/db
    username: ****
    password: ****
    driver-class-name: com.mysql.jdbc.Driver

  activemq:
    broker-url: tcp://******
    user: ******
    password: ******
    in-memory: true

  jms:
    pub-sub-domain: true

  mail:
    host: smtp.163.com
    username: ******
    password: ******
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
    port: 25

  thymeleaf:
    cache: false


#虚拟网关IP、端口和传输内容
firevgw:
  serviceHost: 101.236.42.190
  port: 12346
  message: currentMode

#数据库
mysql:
  sql: SELECT username FROM userinfo WHERE username = 'admin'
  expectResult: admin

#web服务器
web:
  requestUrl: http://101.236.44.31:8080/fireinfo/user/login.do

#mq服务器
mq:
  topicName: fireinfohealthcheck
  message:  ActiveMQ service is health!

#接收邮箱
mail:
  username: ******

#应用端口
server:
  port: 8090

#服务器平台
platform:
  name: 美团云

#日志相关
logging:
  file: F:\\healthcheck\\log\\healthcheck.log




